In [1]:
import numpy as np
np.__version__

'1.14.0'

In [2]:
# 不同于 Python 列表，NumPy 要求数组必须包含同一类型的数据。如果类型不匹配，
# NumPy 将会向上转换（如果可行）。这里整型被转换为浮点型：
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [3]:
# 如果希望明确设置数组的数据类型，可以用 dtype 关键字
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [7]:
np.random.random((3,3))

array([[0.67304955, 0.83352977, 0.15171708],
       [0.48960421, 0.72539136, 0.64859426],
       [0.44523976, 0.27465974, 0.20683067]])

In [8]:
np.random.normal(0, 1, (3, 3))

array([[ 1.19695877, -1.34668886, -0.5276617 ],
       [-0.38548006,  0.19504387,  1.05074328],
       [-0.15409831,  1.02305609, -0.6689631 ]])

In [9]:
np.random.randint(0, 10, (3, 3))

array([[1, 6, 8],
       [3, 5, 1],
       [1, 4, 6]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# 使用NumPy的随机数生成器设置一组种子值，以确保程序每次生成同样的随机数组
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3, 4)) # 二维数组
x3 = np.random.randint(10, size=(3, 4, 5)) # 三维数组

In [19]:
print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [26]:
print(x1)
# Python 列表不同，NumPy 数组是固定类型的。这意味着当你试图将一个浮点
# 值插入一个整型数组时，浮点值会被截短成整型
x1[0] = 3.14
print(x1)

[3 0 3 3 7 9]
[3 0 3 3 7 9]


In [27]:
# 数组的切片
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# 所有元素，逆序的
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
# 从索引5开始每隔一个元素逆序
x[5::-2] 

array([5, 3, 1])

In [31]:
# 多维子数组
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [32]:
x2[:2, :3] # 两行三列

array([[3, 5, 2],
       [7, 6, 8]])

In [33]:
# 所有行，每隔一列
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [39]:
# x2的第一列
print(x2[:, 0])

[3 7 1]


In [44]:
print(x2[0, :])

[3 5 2 4]


In [45]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [46]:
# 通过变形获得的列向量
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [49]:
# 数组的拼接和分裂
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [50]:
# 一次性拼接两个以上数组：
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# np.concatenate 也可以用于二维数组的拼接：
grid = np.array( [[1,2,3],[4,5,6]])
# 沿第一个轴拼接
print('按行拼接\n',np.concatenate([grid, grid]), '\n')
# 沿第二个轴拼接
print('按列拼接\n', np.concatenate([grid, grid], axis=1))

按行拼接
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] 

按列拼接
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [59]:
# 沿着固定维度处理数组时，使用 np.vstack（垂直栈）和 np.hstack（水平栈）函数会更简洁：
x = np.array([1, 2, 3])
grid = np.array([[4,5,6], [7,8,9]])
# 垂直栈数组
np.vstack((x, grid))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
# 水平栈数组
y = np.array([[99], [99]])
np.hstack((grid, y))

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

In [65]:
# 数组的分裂
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [66]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
upper, lower = np.split(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [68]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
